"""
models/mock_llm.py
──────────────────
Data-driven MockLLM for demo / offline mode.

Rather than returning static canned text, this mock:
  1. Parses the incoming prompt to identify the task type.
  2. Loads the relevant sample JSON via utils/data_loader.
  3. Computes real statistics from the data.
  4. Composes a structured, multi-paragraph response that references
     actual data values — making demo mode feel like genuine AI analysis.

Implements the LangChain BaseLLM interface so it is a drop-in replacement
for WatsonxLLM throughout the application.
"""

from __future__ import annotations

import logging
import textwrap
from typing import Any, List, Optional

logger = logging.getLogger(__name__)

# ── LangChain base class ──────────────────────────────────────────────────────
try:
    from langchain_core.language_models.llms import LLM
except ImportError:
    from langchain.llms.base import LLM  # type: ignore[no-redef]


class MockLLM(LLM):
    """
    Offline, data-driven LLM for demo mode.

    All responses are generated by inspecting the bundled sample data files
    and formatting real statistics into readable market-research prose.
    """

    # LangChain requires these fields to be declared as class-level annotations
    # when using Pydantic v2 (which newer LangChain versions use).
    class Config:
        arbitrary_types_allowed = True

    @property
    def _llm_type(self) -> str:
        return "mock"

    def _call(
        self,
        prompt: str,
        stop: Optional[List[str]] = None,
        run_manager: Optional[Any] = None,
        **kwargs: Any,
    ) -> str:
        """Route prompt to the appropriate response builder based on task type."""
        pl = prompt.lower()

        if any(w in pl for w in ["sentiment", "review", "customer feedback", "opinion"]):
            return self._build_sentiment_response()
        if any(w in pl for w in ["competitor", "comparison", "market share", "rival"]):
            return self._build_competitor_response()
        if any(w in pl for w in ["trend", "keyword", "search volume", "growing"]):
            return self._build_trend_response()
        if any(w in pl for w in ["demand", "demand index", "demand forecast", "demand indicator"]):
            return self._build_demand_response()
        if any(w in pl for w in ["full report", "generate report", "market report", "research report"]):
            return self._build_report_response()
        if any(w in pl for w in ["news", "article", "headline", "recent development"]):
            return self._build_news_response()
        if any(w in pl for w in ["document", "retrieved", "context", "according to", "based on"]):
            return self._build_rag_response(prompt)
        return self._build_generic_response()

    # ── Response builders ─────────────────────────────────────────────────────

    def _build_sentiment_response(self) -> str:
        from utils.data_loader import load_reviews, get_sentiment_summary
        reviews = load_reviews()
        ss = get_sentiment_summary()
        if not ss:
            return "Insufficient review data available for sentiment analysis."

        # Top positive and negative review samples
        positives = [r for r in reviews if r.get("sentiment") == "positive"][:3]
        negatives = [r for r in reviews if r.get("sentiment") == "negative"][:2]

        pos_excerpts = "\n".join(
            f'  • ({r["product"]}, ★{r["rating"]}) "{r["review_text"][:120]}..."'
            for r in positives
        )
        neg_excerpts = "\n".join(
            f'  • ({r["product"]}, ★{r["rating"]}) "{r["review_text"][:120]}..."'
            for r in negatives
        )

        # Product-level breakdown
        from collections import defaultdict
        prod_ratings: dict[str, list[int]] = defaultdict(list)
        for r in reviews:
            prod_ratings[r["product"]].append(r["rating"])
        prod_avg = {p: round(sum(v)/len(v), 2) for p, v in prod_ratings.items()}
        top_product = max(prod_avg, key=lambda p: prod_avg[p])
        low_product = min(prod_avg, key=lambda p: prod_avg[p])

        return textwrap.dedent(f"""
        ## 🤖 AI Analysis — Customer Sentiment Report

        **Overview**
        Analysis of {ss['total_reviews']} customer reviews reveals an overall **positive market sentiment**,
        with {ss['positive_pct']}% of reviews classified as positive, {ss['neutral_pct']}% neutral, and
        {ss['negative_pct']}% negative. The mean star rating across all products is **{ss['avg_rating']}/5.0**.

        **Product-Level Highlights**
        - Highest-rated product: **{top_product}** (avg {prod_avg[top_product]}/5.0)
        - Lowest-rated product: **{low_product}** (avg {prod_avg[low_product]}/5.0)

        **Representative Positive Feedback**
        Customers consistently praise enterprise reliability, developer experience, and AI model quality:
{pos_excerpts}

        **Representative Negative Feedback**
        Key pain points include customer support responsiveness, pricing transparency, and product innovation pace:
{neg_excerpts}

        **Key Themes Identified**
        1. *Developer experience* is the top differentiator for mid-market customers.
        2. *Pricing transparency* is the most common source of negative reviews.
        3. *Support responsiveness* and *AI capability depth* are critical for enterprise renewal decisions.
        4. Customers in regulated industries (banking, healthcare) prioritise compliance features over price.

        **Sentiment Trend**
        Reviews from Q3/Q4 2024 show improving sentiment for cloud-native providers and declining sentiment
        for legacy incumbents — reflecting the broader market shift toward modern, AI-first platforms.

        > 🔮 *Forecast / Interpretation:* If support and pricing transparency issues remain unresolved,
        > the negative review share is likely to grow. Providers that invest in self-service tooling and
        > clearer billing are projected to see 8–12% improvement in NPS scores over the next two quarters.
        > This is an analytical projection, not a guaranteed outcome.
        """).strip()

    def _build_competitor_response(self) -> str:
        from utils.data_loader import load_competitors
        competitors = load_competitors()
        if not competitors:
            return "No competitor data available."

        # Sort by market share descending
        ranked = sorted(competitors, key=lambda c: c.get("market_share", 0), reverse=True)
        leader = ranked[0]
        challenger = ranked[1]
        fastest_grower = max(
            competitors,
            key=lambda c: c.get("market_share", 0) - c.get("market_share_prev", 0),
        )
        losing = min(
            competitors,
            key=lambda c: c.get("market_share", 0) - c.get("market_share_prev", 0),
        )

        table_rows = "\n".join(
            f"| {c['name']} | {c['market_share']}% | {c['market_share_prev']}% "
            f"| {c['market_share'] - c['market_share_prev']:+.1f}pp | ${c['revenue_bn']}B |"
            for c in ranked
        )

        return textwrap.dedent(f"""
        ## 🤖 AI Analysis — Competitive Landscape

        **Market Share Overview**

        | Company | Current Share | Prior Share | Change | Revenue |
        |---|---|---|---|---|
        {table_rows}

        **Market Leader — {leader['name']} ({leader['market_share']}%)**
        {leader['name']} dominates with a {leader['market_share']}% share and ${leader['revenue_bn']}B in revenue.
        Key strengths: {'; '.join(leader['strengths'][:2])}.
        Recent activity: {leader['recent_activities'][0]}.

        **Strongest Challenger — {challenger['name']} ({challenger['market_share']}%)**
        {challenger['name']} is the closest rival, growing from {challenger['market_share_prev']}% to
        {challenger['market_share']}% through {challenger['growth_strategy'].lower()}.
        Entry pricing at {challenger['pricing']['entry_plan']} makes it accessible to mid-market buyers.

        **Fastest Growing — {fastest_grower['name']}**
        {fastest_grower['name']} recorded the largest share gain ({fastest_grower['market_share'] - fastest_grower['market_share_prev']:+.1f}pp),
        driven by: {fastest_grower['recent_activities'][0]}.

        **Losing Ground — {losing['name']}**
        {losing['name']} lost {abs(losing['market_share'] - losing['market_share_prev']):.1f}pp of share.
        Weaknesses: {'; '.join(losing['weaknesses'][:2])}.

        **Strategic Implications**
        1. The market is bifurcating between AI-native challengers and legacy incumbents.
        2. Developer-led growth strategies (NovaTech, CloudSpark) are outperforming traditional enterprise sales.
        3. Compliance and vertical specialisation remain defensible moats for regulated industries.
        4. Mid-market pricing pressure is intensifying as newer entrants undercut incumbent pricing by 40–60%.

        > 🔮 *Forecast / Interpretation:* Based on current share trajectory, {fastest_grower['name']} is on
        > track to surpass {ranked[2]['name']} in market share within 2–3 quarters. This projection is based
        > on observed trend lines and does not account for unannounced product launches or M&A activity.
        """).strip()

    def _build_trend_response(self) -> str:
        from utils.data_loader import load_trends, get_fastest_growing_keyword
        trends = load_trends()
        if not trends:
            return "No trend data available."

        fgk = get_fastest_growing_keyword()

        # Per-keyword stats: latest volume, avg monthly growth, total growth Jan→Dec
        from collections import defaultdict
        kw_data: dict[str, list[dict]] = defaultdict(list)
        for row in trends:
            kw_data[row["keyword"]].append(row)

        summary_lines = []
        for kw, rows in sorted(kw_data.items()):
            rows_sorted = sorted(rows, key=lambda r: r["month"])
            vol_start = rows_sorted[0]["volume"]
            vol_end = rows_sorted[-1]["volume"]
            total_growth = round((vol_end - vol_start) / vol_start * 100, 1)
            avg_monthly = round(sum(r["growth_pct"] for r in rows) / len(rows), 1)
            peak_month = max(rows, key=lambda r: r["growth_pct"])
            summary_lines.append(
                f"| {kw} | {vol_end:,} | +{total_growth}% | {avg_monthly}% | "
                f"{peak_month['month']} ({peak_month['growth_pct']:+}%) |"
            )

        table = "\n".join(summary_lines)

        # Notable events
        cyber_spike = next(
            (r for r in trends if r["keyword"] == "Cybersecurity" and r["growth_pct"] > 20),
            None,
        )
        ecom_spike = next(
            (r for r in trends if r["keyword"] == "E-commerce" and r["growth_pct"] > 12),
            None,
        )

        notable = ""
        if cyber_spike:
            notable += (
                f"\n- **Cybersecurity spike in {cyber_spike['month']}** "
                f"(+{cyber_spike['growth_pct']}% MoM) correlates with the CrowdStrike incident "
                f"and subsequent enterprise security reviews."
            )
        if ecom_spike:
            notable += (
                f"\n- **E-commerce surge in {ecom_spike['month']}** "
                f"(+{ecom_spike['growth_pct']}% MoM) reflects the holiday shopping season ramp-up "
                f"and TikTok Shop market penetration."
            )

        return textwrap.dedent(f"""
        ## 🤖 AI Analysis — Market Trend Report (Jan–Dec 2024)

        **Keyword Volume Summary**

        | Keyword | Dec 2024 Volume | YTD Growth | Avg Monthly Growth | Peak Month |
        |---|---|---|---|---|
        {table}

        **Top Trend: {fgk['keyword']}**
        {fgk['keyword']} is the fastest-growing topic with an average monthly growth rate of
        {fgk['avg_growth_pct']}%. This sustained acceleration reflects enterprise adoption moving
        from pilots to production deployments, infrastructure investment, and growing media coverage.

        **Notable Events**{notable if notable else " No statistically significant spikes detected."}

        **Cross-Keyword Analysis**
        - AI and Cloud are structurally correlated — AI workload growth is directly driving cloud
          infrastructure demand, creating a reinforcing demand cycle.
        - Cybersecurity shows event-driven volatility layered on top of a steady structural uptrend.
        - E-commerce exhibits strong seasonality, with Q4 volumes 20–30% above Q1 baselines.
        - Fintech shows the most consistent, linear growth — reflecting steady regulatory-driven
          digitisation rather than hype cycles.

        > 🔮 *Forecast / Interpretation:* Extrapolating current growth rates into Q1 2025,
        > AI search volume is projected to exceed 220,000 monthly queries, representing 168%
        > growth over the January 2024 baseline. These are trend-based projections and should
        > be interpreted as directional indicators, not guaranteed outcomes.
        """).strip()

    def _build_demand_response(self) -> str:
        from utils.data_loader import load_demand, get_demand_summary
        demand = load_demand()
        if not demand:
            return "No demand data available."

        ds = get_demand_summary()

        # Q4 2024 summary per category
        q4 = [d for d in demand if d.get("quarter") == "Q4 2024"]
        from collections import defaultdict
        cat_data: dict[str, list[dict]] = defaultdict(list)
        for row in q4:
            cat_data[row["category"]].append(row)

        table_rows = []
        for cat, rows in sorted(cat_data.items()):
            avg_idx = round(sum(r["demand_index"] for r in rows) / len(rows), 1)
            avg_yoy = round(sum(r["yoy_change"] for r in rows) / len(rows), 1)
            top_region = max(rows, key=lambda r: r["demand_index"])["region"]
            table_rows.append(f"| {cat} | {avg_idx} | +{avg_yoy}% YoY | {top_region} |")

        table = "\n".join(table_rows)

        return textwrap.dedent(f"""
        ## 🤖 AI Analysis — Market Demand Report (Q4 2024)

        **Demand Index by Category — Q4 2024**

        | Category | Avg Demand Index | YoY Change | Strongest Region |
        |---|---|---|---|
        {table}

        **Highest Demand Segment**
        {ds.get('top_category', 'N/A')} in {ds.get('top_region', 'N/A')} recorded the highest demand
        index of **{ds.get('demand_index', 'N/A')}** in Q4 2024, representing a
        {ds.get('yoy_change', 'N/A')}% year-over-year increase.

        **Regional Dynamics**
        - **Asia-Pacific** consistently shows the highest growth rates across all categories,
          driven by digital transformation investment in India, Southeast Asia, and South Korea.
        - **North America** records the highest absolute demand indices, reflecting its mature
          technology adoption base and higher enterprise spending per capita.
        - **Europe** shows steady but more moderate growth, constrained by regulatory caution
          around AI deployment and tighter enterprise budget cycles.

        **Category Insights**
        - *AI Software* demand is growing fastest (avg 22–31% YoY depending on region),
          driven by generative AI production deployments.
        - *Cybersecurity* shows an unusual Q3 spike due to the CrowdStrike incident triggering
          emergency security reviews across enterprise IT departments.
        - *E-commerce Platform* demand spikes sharply in Q4, consistent with holiday season
          technology investment patterns.

        > 🔮 *Forecast / Interpretation:* AI Software demand in Asia-Pacific is projected to
        > surpass North America in absolute index by Q3 2025 if current growth differentials are
        > maintained. This is a model-based projection and actual outcomes will depend on
        > regulatory developments, macroeconomic conditions, and competitive dynamics.
        """).strip()

    def _build_news_response(self) -> str:
        from utils.data_loader import load_news
        news = load_news()
        if not news:
            return "No news data available."

        # Top 5 by relevance
        top5 = sorted(news, key=lambda n: n.get("relevance_score", 0), reverse=True)[:5]
        articles = "\n".join(
            f"  {i+1}. **{a['title']}** ({a['source']}, {a['published_at']})\n"
            f"     {a['description'][:180]}..."
            for i, a in enumerate(top5)
        )

        # Category breakdown
        from collections import Counter
        cats = Counter(a.get("category", "Other") for a in news)
        cat_summary = ", ".join(f"{cat}: {cnt}" for cat, cnt in cats.most_common())

        return textwrap.dedent(f"""
        ## 🤖 AI Analysis — News & Market Intelligence Summary

        **Coverage Breakdown** ({len(news)} articles indexed)
        {cat_summary}

        **Top 5 Most Relevant Articles**
        {articles}

        **Key Themes from Recent Coverage**

        1. *AI Infrastructure Investment:* NVIDIA's record $35.1B quarter and hyperscaler AI
           spending surges indicate infrastructure buildout is in full swing. Enterprises should
           anticipate continued GPU supply constraints through H1 2025.

        2. *Regulatory Pressure:* EU AI Act implementation and US sector-specific guidance are
           creating compliance overhead. Companies with established governance frameworks have
           a first-mover advantage.

        3. *Market Consolidation:* TechAlpha's $1.2B acquisition of DataSense AI signals that
           M&A will accelerate as incumbents seek to close capability gaps with pure-play AI startups.

        4. *Security Risk Elevation:* The CrowdStrike incident and rising breach costs ($4.88M avg)
           have elevated cybersecurity from IT concern to board-level strategic priority.

        5. *Social Commerce Disruption:* TikTok Shop's 5% US e-commerce share capture in its first
           year demonstrates how quickly algorithm-driven discovery models can disrupt established
           marketplace hierarchies.

        > 🔮 *Forecast / Interpretation:* Based on news signal analysis, AI infrastructure and
        > cybersecurity will be the two highest-conviction growth themes through 2025.
        > These are analytical observations based on news pattern analysis, not investment advice.
        """).strip()

    def _build_rag_response(self, prompt: str) -> str:
        from utils.data_loader import load_sample_report_texts
        reports = load_sample_report_texts()

        if not reports:
            return "No documents are currently indexed. Please upload a report to ask document-specific questions."

        # Simple keyword-based snippet extraction from reports
        prompt_keywords = [w for w in prompt.lower().split() if len(w) > 4]
        best_report = None
        best_score = -1
        for report in reports:
            score = sum(1 for kw in prompt_keywords if kw in report["text"].lower())
            if score > best_score:
                best_score = score
                best_report = report

        if not best_report:
            best_report = reports[0]

        # Extract a relevant paragraph
        paragraphs = [p.strip() for p in best_report["text"].split("\n\n") if len(p.strip()) > 100]
        relevant_para = ""
        if paragraphs:
            scored_paras = sorted(
                paragraphs,
                key=lambda p: sum(1 for kw in prompt_keywords if kw in p.lower()),
                reverse=True,
            )
            relevant_para = scored_paras[0] if scored_paras else paragraphs[0]

        return textwrap.dedent(f"""
        ## 📄 Retrieved Evidence

        **Source:** {best_report['filename']}

        > {relevant_para[:500]}{'...' if len(relevant_para) > 500 else ''}

        ---

        ## 🤖 AI Analysis

        Based on the indexed market reports, the relevant context for your query has been retrieved above.

        Key findings from the document corpus:
        - The global technology market is estimated at $5.8 trillion with 12.4% YoY growth.
        - AI software spending reached $235 billion in 2024, up 41% from 2023.
        - Cloud infrastructure spending totalled $720 billion globally.
        - Enterprise AI production deployment reached 68% of Fortune 1000 companies.
        - Three strategic imperatives: AI governance, data infrastructure investment, and hybrid architectures.

        The retrieved document provides the primary evidence base. The analysis above synthesises
        the document content with broader market context.

        > 🔮 *Forecast / Interpretation:* Forward-looking statements in the source documents
        > represent the analysts' projections at time of writing and should not be treated as
        > guaranteed outcomes.
        """).strip()

    def _build_report_response(self) -> str:
        from utils.data_loader import (
            get_top_competitor, get_fastest_growing_keyword,
            get_sentiment_summary, get_demand_summary, load_competitors,
        )
        tc = get_top_competitor()
        fgk = get_fastest_growing_keyword()
        ss = get_sentiment_summary()
        ds = get_demand_summary()
        competitors = load_competitors()
        ranked = sorted(competitors, key=lambda c: c.get("market_share", 0), reverse=True)

        comp_table = "\n".join(
            f"| {c['name']} | {c['market_share']}% | ${c['revenue_bn']}B | "
            f"{c['market_share'] - c['market_share_prev']:+.1f}pp |"
            for c in ranked
        )

        return textwrap.dedent(f"""
        # 📊 Intelligent Market Research Report
        **Generated by IBM Granite Market Research Assistant — Q4 2024**
        *Note: This report was generated in Demo Mode using the data-driven MockLLM and bundled sample data.*

        ---

        ## Executive Summary

        The global technology market is experiencing transformational growth driven by artificial intelligence
        adoption, cloud infrastructure expansion, and heightened cybersecurity investment. Total market size
        is estimated at **$5.8 trillion** with 12.4% year-over-year growth. AI remains the highest-conviction
        growth theme, with search volume growing an average of **{fgk['avg_growth_pct']}% per month** throughout
        2024. Customer sentiment is broadly positive at **{ss['positive_pct']}%** across {ss['total_reviews']}
        reviewed products, with an average rating of **{ss['avg_rating']}/5.0**.

        ---

        ## 1. Market Overview

        The technology sector continues its structural expansion, with five primary growth engines:

        | Segment | 2024 Market Size | YoY Growth |
        |---|---|---|
        | AI Software & Services | $235B | +41% |
        | Cloud Infrastructure | $720B | +22% |
        | Cybersecurity | $215B | +14% |
        | E-commerce | $6,300B | +9% |
        | Fintech | $340B | +8% |

        The inflection point for generative AI is confirmed: 68% of Fortune 1000 companies now run
        at least one generative AI application in production, up from 24% in 2023.

        ---

        ## 2. Competitive Landscape

        | Company | Market Share | Revenue | Share Change |
        |---|---|---|---|
        {comp_table}

        **Market Leader:** {tc.get('name', 'N/A')} holds {tc.get('market_share', 'N/A')}% of the market
        with ${tc.get('revenue_bn', 'N/A')}B in revenue. Recent M&A activity (DataSense AI acquisition for
        $1.2B) strengthens its analytics capabilities and enterprise data moat.

        **Key Competitive Dynamics:**
        - Developer-led challengers (NovaTech, CloudSpark) are gaining share at the expense of legacy incumbents
        - Pricing pressure is intensifying — new entrants undercut incumbents by 40–60% on comparable workloads
        - Compliance and vertical specialisation remain defensible moats in regulated industries

        ---

        ## 3. Customer Sentiment Analysis

        📄 *Based on {ss['total_reviews']} customer reviews across all tracked products.*

        - **{ss['positive_pct']}%** positive | **{ss['neutral_pct']}%** neutral | **{ss['negative_pct']}%** negative
        - Average star rating: **{ss['avg_rating']}/5.0**
        - Top positive theme: developer experience, AI model quality, enterprise reliability
        - Top negative theme: pricing transparency, support responsiveness, slow innovation pace

        ---

        ## 4. Trend Analysis

        📄 *Based on 12-month keyword volume data (Jan–Dec 2024).*

        **Fastest growing keyword: {fgk['keyword']}** (+{fgk['avg_growth_pct']}% average monthly growth)

        Notable trend events:
        - Cybersecurity volume spiked +26.4% MoM in July 2024 following the CrowdStrike incident
        - E-commerce volume surged +16.0% in November 2024 (holiday season)
        - AI volume maintained consistent double-digit growth every month of 2024

        ---

        ## 5. Demand Analysis

        📄 *Based on demand index data across categories and regions.*

        Highest demand segment: **{ds.get('top_category', 'N/A')}** in **{ds.get('top_region', 'N/A')}**
        (Demand Index: {ds.get('demand_index', 'N/A')}, YoY Change: +{ds.get('yoy_change', 'N/A')}%)

        Asia-Pacific is the fastest-growing region across all categories, while North America retains
        the highest absolute demand indices.

        ---

        ## 6. Key Competitor Activities

        - **TechAlpha Corp:** Acquired DataSense AI for $1.2B; launched Cloud AI Platform v4.0 with agentic capabilities
        - **NovaTech Solutions:** Released LLM 3.5 (top-5 benchmarks); raised $650M Series E at $9.1B valuation
        - **CloudSpark Inc:** Filed for IPO; crossed 1,000 enterprise customers; won Gartner Cool Vendor 2024
        - **Apex Digital Systems:** Divested analytics division; announced 18-month AI transformation roadmap
        - **Meridian AI Labs:** Secured $200M Series B; signed first enterprise deal with Mayo Clinic

        ---

        ## 7. Actionable Recommendations

        1. **Prioritise AI governance frameworks** before scaling AI deployments — regulatory compliance
           is transitioning from optional to mandatory across all major markets.

        2. **Evaluate cloud-native challengers** (CloudSpark, NovaTech) for 40–60% cost savings on
           comparable workloads versus incumbent pricing.

        3. **Increase cybersecurity posture** — the $4.88M average breach cost and regulatory pressure
           make security investment one of the highest-ROI technology decisions.

        4. **Invest in social commerce capabilities** — TikTok Shop's rapid market capture demonstrates
           the need to diversify channel strategy beyond traditional e-commerce marketplaces.

        5. **Monitor Asia-Pacific demand signals** — the region is outpacing other geographies and
           represents the highest-growth opportunity for technology vendors.

        ---

        ## Disclaimer

        > 🔮 *This report contains forecasts and analytical interpretations generated by an AI system.
        > Projections are based on trend extrapolation from the available sample data and should not be
        > treated as guaranteed outcomes. All forward-looking statements are subject to market, regulatory,
        > and competitive risks. This report is intended for educational and demonstration purposes.*

        ---
        *Report generated by Intelligent Market Research Assistant (Demo Mode) — IBM Granite Powered*
        """).strip()

    def _build_generic_response(self) -> str:
        from utils.data_loader import (
            get_top_competitor, get_fastest_growing_keyword, get_sentiment_summary,
        )
        tc = get_top_competitor()
        fgk = get_fastest_growing_keyword()
        ss = get_sentiment_summary()

        return textwrap.dedent(f"""
        ## 🤖 AI Analysis — Market Research Summary

        Based on the available market intelligence data, here is a high-level snapshot of the current
        technology market landscape:

        **Market Position**
        - Market leader: **{tc.get('name', 'N/A')}** with {tc.get('market_share', 'N/A')}% market share
          and ${tc.get('revenue_bn', 'N/A')}B in annual revenue
        - Total tracked competitors: 5, covering AI software, cloud infrastructure, and enterprise platforms

        **Trend Signals**
        - Fastest growing topic: **{fgk.get('keyword', 'N/A')}** at {fgk.get('avg_growth_pct', 'N/A')}%
          average monthly growth
        - Strong seasonal patterns in E-commerce (Q4 surge) and event-driven spikes in Cybersecurity

        **Customer Sentiment**
        - Overall sentiment: **{ss.get('positive_pct', 'N/A')}% positive** across {ss.get('total_reviews', 0)} reviews
        - Average product rating: **{ss.get('avg_rating', 'N/A')}/5.0**
        - Key insight: Developer experience and pricing transparency are the top drivers of sentiment variance

        **Recommended Next Steps**
        You can ask me to:
        - *"Analyse customer sentiment in detail"* — for a full sentiment breakdown
        - *"Compare competitors"* — for market share analysis and strategic insights
        - *"Show market trends"* — for keyword volume and growth analysis
        - *"Analyse demand"* — for regional demand index breakdown
        - *"Summarise recent news"* — for latest market intelligence
        - *"Generate a full report"* — for a complete market research document with PDF export

        > 📄 *You can also upload PDF, DOCX, or TXT documents to ask questions about your own market reports.*

        > 🔮 *Forecast / Interpretation:* All trend projections and demand forecasts are analytical
        > estimates based on available data. They are not guaranteed future outcomes.
        """).strip()
